Repository DiegoArruda/bibliotech-squad3, pull requests merged in 2023-04, with the labels that each got.

#59 politicas privacidade
  .vscode/launch.json
  src/App.jsx
  src/pages/Politicas/politicas.jsx
Labels: enhancement

#60 Delay de F5 da página corrigido
  src/App.jsx
  src/pages/Root/Root.jsx
Labels: enhancement

#61 Load screen costumizada
  src/components/Loader/Loader.jsx
Labels: enhancement

#62 Footer
  src/App.jsx
  src/assets/images/logo1.png
  src/components/Footer/Footer.jsx
  src/firebase/config.js
  src/pages/Cadastro/Cadastro.jsx
  src/pages/Login/Login.jsx
  src/pages/Root/Root.jsx
Labels: enhancement

#63 Dark theme
  package-lock.json
  package.json
  src/App.css
  src/App.jsx
  src/components/Menu/Menu.jsx
  src/contexts/ThemeContext.js
  src/index.jsx
  src/pages/Emprestimos/Emprestimos.jsx
  src/pages/Home/Home.jsx
  src/pages/Livros/Livros.css
  src/pages/Livros/Livros.jsx
  src/pages/Root/Root.jsx
Labels: enhancement

#64 Correção de erros
  src/pages/Cadastro/Cadastro.jsx
  src/pages/Login/Login.jsx
Labels: bug

#65 Delete livros
  src/App.css
  src/pages/Cadastro/Cadastro.jsx
  src/pages/Login/Login.jsx
Labels: bug, enhancement

#67 Página do Quiz
  src/App.jsx
  src/pages/Cadastro/Cadastro.jsx
  src/pages/Login/Login.jsx
  src/pages/Quizz/Quizz.css
  src/pages/Quizz/Quizz.jsx
Labels: enhancement

#69 Devolucao emprestimo
  dayjs.txt
  package-lock.json
  package.json
  src/App.jsx
  src/pages/AdicionarEmprestimo/AdicionarEmprestimo.jsx
  src/pages/Emprestimos/Emprestimos.jsx
  src/pages/Livros/Livros.jsx
  src/pages/Quizz/Quizz.css
  src/pages/Quizz/Quizz.jsx
  src/pages/Root/Root.jsx
Labels: enhancement

#71 Correção de acesso ao gadastro do usuario logado
  src/pages/Cadastro/Cadastro.jsx
  src/pages/Livros/Livros.jsx
Labels: enhancement

#72 Página de Loja
  src/App.jsx
  src/pages/Cadastro/Cadastro.jsx
  src/pages/Livros/Livros.jsx
  src/pages/Login/Login.jsx
  src/pages/Loja/Loja.css
  src/pages/Loja/Loja.jsx
  src/pages/Loja/ModalLoja.jsx
  src/pages/Quizz/Quizz.jsx
Labels: enhancement

#73 Switch state emprestimo
  src/pages/AdicionarEmprestimo/AdicionarEmprestimo.jsx
  src/pages/Cadastro/Cadastro.jsx
  src/pages/Emprestimos/Emprestimos.jsx
Labels: enhancement

#76 finalização home
  src/pages/Home/Home.css
  src/pages/Home/Home.jsx
Labels: enhancement

#77 Estilização
  src/components/Footer/Footer.css
  src/components/Footer/Footer.jsx
  src/pages/Cadastro/Cadastro.jsx
  src/pages/Login/Login.css
  src/pages/Login/Login.jsx
  src/pages/Root/Root.jsx
Labels: enhancement

#78 Vesão omega plus litte do Bibliotech
  src/App.css
  src/assets/icons/LogoBibliotech.svg
  src/assets/icons/LogoBibliotechSemTitulo.svg
  src/assets/images/Loja/Bem-Vindo.jpeg
  src/assets/images/Loja/Happy.jpeg
  src/assets/images/Loja/Presente.jpeg
  src/assets/images/logo1.png
  src/assets/images/paginaAjuda/Ajuda1.jpg
  src/assets/images/paginaAjuda/Ajuda2.jpg
  src/assets/images/paginaAjuda/Ajuda3.jpg
  src/assets/images/paginaAjuda/cadastro1.png
  src/assets/images/paginaAjuda/editar1.png
  src/assets/images/paginaAjuda/emprestar1.png
  src/assets/images/paginaAjuda/status1.png
  src/components/Footer/Footer.css
  src/components/Footer/Footer.jsx
  src/components/Loader/Loader.jsx
  src/components/Menu/Menu.jsx
  src/pages/Cadastro/Cadastro.jsx
  src/pages/Home/Home.css
  src/pages/Home/Home.jsx
  src/pages/Login/Login.css
  src/pages/Login/Login.jsx
  src/pages/Loja/Loja.css
  src/pages/Loja/Loja.jsx
  src/pages/PaginaAjuda/PaginaAjuda.jsx
  src/pages/Politicas/politicas.jsx
  src/pages/Quizz/Quizz.jsx
  src/pages/RecuperarSenha/RecuperarSenha.jsx
  src/pages/Root/Root.css
  src/pages/Root/Root.jsx
Labels: bug, enhancement

#79 Atualização
  src/App.css
  src/pages/Loja/Loja.css
  src/pages/Loja/Loja.jsx
Labels: bug
